apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: odh-trustyai-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odh-trustyai-service
    app.kubernetes.io/part-of: trustyai
  name: odh-trustyai-service
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: odh-trustyai-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: odh-trustyai-service
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/trustyai/odh-trustyai-service@sha256:c224e2d39617dea0b69bb4e57a225c7d119c154f4bbd80a3e998d07713009766
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
